In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv('dataset.csv')

In [5]:
dataset

,iso,country,date,grocery_pharmacy,parks,residential,retail_recreation,transit_stations,workplaces,total_cases,fatalities
0,AR,Argentina,2020-02-23,8.185,17.563,0.437,13.644,5.334,-2.486,0,0
1,AR,Argentina,2020-02-24,-15.875,25.605,6.321,-9.973,-26.785,-53.687,0,0
2,AR,Argentina,2020-02-25,-17.135,1.325,6.895,-19.717,-28.485,-50.053,0,0
3,AR,Argentina,2020-02-26,2.304,5.399,-2.273,0.845,9.461,12.584,0,0
4,AR,Argentina,2020-02-27,-0.404,-5.267,-0.493,-0.584,7.983,12.407,0,0
...,...,...,...,...,...,...,...,...,...,...,...
812,ZA,South Africa,2020-04-01,-42.446,-37.600,34.916,-69.728,-77.371,-72.935,1380,5
813,ZA,South Africa,2020-04-02,-40.523,-38.226,36.550,-69.577,-77.874,-73.331,1462,5
814,ZA,South Africa,2020-04-03,-42.107,-43.271,38.379,-71.513,-77.944,-72.745,1505,9
815,ZA,South Africa,2020-04-04,-51.515,-57.252,26.499,-76.589,-77.026,-55.095,1585,9
816,ZA,South Africa,2020-04-05,-51.420,-53.273,22.351,-75.913,-78.001,-44.329,1655,11

In [13]:
data_matrix = dataset.iloc[:,:-1].values

In [14]:
data_matrix

array([['AR', 'Argentina', '2020-02-23', ..., 5.334, -2.4859999999999998,
        0],
       ['AR', 'Argentina', '2020-02-24', ..., -26.785, -53.687, 0],
       ['AR', 'Argentina', '2020-02-25', ..., -28.485,
        -50.053000000000004, 0],
       ...,
       ['ZA', 'South Africa', '2020-04-03', ..., -77.944, -72.745, 1505],
       ['ZA', 'South Africa', '2020-04-04', ..., -77.02600000000001,
        -55.095, 1585],
       ['ZA', 'South Africa', '2020-04-05', ..., -78.001,
        -44.32899999999999, 1655]], dtype=object)

In [16]:
#Tratar das  variÃ¡veis categÃ³ricas
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
data_matrix[:,0] = labelencoder_X.fit_transform(data_matrix[:,0])
#onehotencoder = OneHotEncoder(categorical_features = [0])
#data_matrix = onehotencoder.fit_transform(data_matrix).toarray()